//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNU.Getopt.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GNU.Getopt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: option &apos;&apos;{1}&apos;&apos; is ambiguous.
        /// </summary>
        internal static string getoptAmbigious {
            get {
                return ResourceManager.GetString("getoptAmbigious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: option &apos;&apos;--{1}&apos;&apos; doesn&apos;t allow an argument.
        /// </summary>
        internal static string getoptArguments1 {
            get {
                return ResourceManager.GetString("getoptArguments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: option &apos;&apos;{1}{2}&apos;&apos; doesn&apos;t allow an argument.
        /// </summary>
        internal static string getoptArguments2 {
            get {
                return ResourceManager.GetString("getoptArguments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: illegal option -- {1}.
        /// </summary>
        internal static string getoptIllegal {
            get {
                return ResourceManager.GetString("getoptIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: invalid option -- {1}.
        /// </summary>
        internal static string getoptInvalid {
            get {
                return ResourceManager.GetString("getoptInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid value {0} for parameter &apos;has_arg&apos; .
        /// </summary>
        internal static string getoptInvalidValue {
            get {
                return ResourceManager.GetString("getoptInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: option &apos;&apos;{1}&apos;&apos; requires an argument.
        /// </summary>
        internal static string getoptRequires {
            get {
                return ResourceManager.GetString("getoptRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: option requires an argument -- {1}.
        /// </summary>
        internal static string getoptRequires2 {
            get {
                return ResourceManager.GetString("getoptRequires2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: unrecognized option &apos;&apos;--{1}&apos;&apos;.
        /// </summary>
        internal static string getoptUnrecognized {
            get {
                return ResourceManager.GetString("getoptUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: unrecognized option &apos;&apos;{1}{2}&apos;&apos;.
        /// </summary>
        internal static string getoptUnrecognized2 {
            get {
                return ResourceManager.GetString("getoptUnrecognized2", resourceCulture);
            }
        }
    }
}
